id.description=The ID field is required.
scope.description=Define the access scope. Public accesses are inherited and private accesses are not.
access.description=Define the access mode.
module.description=The MODULE field must be filled with at most 64 letters.
screen.description=The SCREEN field must be filled with at most 64 letters.
action.description=The ACTION field must be filled with at most 64 letters.
