<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.gate-org-br</groupId>
    <artifactId>gate-parent</artifactId>
    <version>21.0.0</version>
    <packaging>pom</packaging>

    <name>gate-parent</name>
    <description>Parent build for the Gate ecosystem</description>
    <url>https://github.com/gate-org-br/gate</url>

    <developers>
        <developer>
            <id>davinunesdasilva</id>
            <name>Davi Nunes da Silva</name>
            <email>davinunesdasilva@gmail.com</email>
        </developer>
    </developers>

    <scm>
        <url>https://github.com/gate-org-br/gate</url>
        <connection>scm:git:https://github.com/gate-org-br/gate.git</connection>
    </scm>

    <licenses>
        <license>
            <distribution>repo</distribution>
            <url>https://www.gnu.org/licenses/lgpl-3.0.en.html</url>
            <name>GNU LESSER GENERAL PUBLIC LICENSE Version 3, 29 June 2007</name>
        </license>
    </licenses>

    <modules>
        <module>modules/core</module>
        <module>modules/security</module>
        <module>modules/sql</module>
        <module>modules/doc</module>
        <module>modules/io</module>
        <module>modules/gate</module>
    </modules>

    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>ossrh</id>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>