id.name=Role
active.name=Active
role.name=Parent Role
manager.name=Manager
name.name=Name
description.name=Description
master.name=Master
rolename.name=Acronym
email.name=Email
recursive.name=Hierarchical Search
id.description=The Role field is required.
active.description=Determines whether the role is active. Users with inactive roles cannot log in.
manager.description=Enter the group's manager.
name.description=The NAME field is required and must be filled with at most 64 characters.
description.description=The DESCRIPTION field must be filled with at most 256 characters.
master.description=Defines whether the role is master.
rolename.description=Enter the group's acronym.
email.description=The EMAIL field must be filled with a valid email up to 64 characters long.
recursive.description=Should the search be performed hierarchically?
