package gate.adapter.jsonRenderer;

import gate.adapter.converter.Converter;
import gate.adapter.registry.JsonRendererRegistry;
import gate.error.ConversionException;
import gate.lang.json.JsonElement;

public interface JsonRenderer
{
	JsonElement renderJson(Class<?> type, Object object);

	/**
	 * Serializes the specified java object on JSON notation
	 * <p>
	 * The specified object will be serialized as described on the specified java type associated
	 * {@link Converter}.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need
	 * for it to have enough information to restore the original object.
	 *
	 * @param object the java object to be serialized
	 * @return the specified java object mapped to a JSON object
	 * @throws ConversionException if the specified object can't be serialized on JSON notation
	 */
	static JsonElement render(Object object)
	{
		if (object == null)
			return null;

		return JsonRendererRegistry.INSTANCE.get(object.getClass())
				.renderJson(object.getClass(), object);

	}
}