package gate.adapter.converter;

import gate.adapter.registry.ConverterRegistry;
import gate.constraint.Constraint;
import gate.error.AppError;
import gate.error.ConversionException;
import gate.util.Reflection;

import java.lang.reflect.Parameter;
import java.lang.reflect.Type;
import java.util.Collection;
import java.util.Collections;

/**
 * Adapts a java class to be used by the gate framework.
 */
public interface Converter
{
	default Collection<Constraint.Implementation<?>> getConstraints()
	{
		return Collections.emptyList();
	}

	/**
	 * Converts the specified java object to a {@link java.lang.Number}.
	 *
	 * @param type   type of the object to be converted to a Number
	 * @param object object to be converted to a Number
	 * @return the specified object as a Number
	 */
	default Number toNumber(Class<?> type, Object object)
	{
		throw new UnsupportedOperationException(
				String.format("Objects of type %s can't be converted to %s.", type.getName(),
						Number.class.getName()));
	}

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method must have all information necessary for it to be
	 * converted back to the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 * @see Converter#ofString
	 */
	String toString(Class<?> type, Object object);

	/**
	 * Converts the specified java object to an ISO string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method must have all information necessary for it to be
	 * converted back to the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 * @see Converter#ofString
	 */
	default String toISOString(Class<?> type, Object object)
	{
		return toString(type, object);
	}

	/**
	 * Converts the specified string back to its original java object.
	 *
	 * @param type   type of the object that originated the specified string
	 * @param string the string to be converted back to its original java object
	 * @return the object that was previously converted to the specified string
	 * @throws gate.error.ConversionException if the specified string can't be converted to its
	 *                                        original java object
	 * @see Converter#toString
	 */
	Object ofString(Type type, String string) throws ConversionException;

	/**
	 * Gets the converter associated with the specified java class.
	 *
	 * @param type java class whose associated converted must be returned
	 * @return the converter associated with the specified java class
	 */
	static Converter getConverter(Class<?> type) {return ConverterRegistry.INSTANCE.get(type);}

	static Converter getConverter(Type type) {return getConverter(Reflection.getRawType(type));}

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The string generated by this method has all information necessary for it to be converted
	 * back to the original object.
	 *
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 */
	static String toString(Object object)
	{
		if (object == null)
			return "";
		Class<?> type = object.getClass();
		return getConverter(type).toString(type, object);
	}

	/**
	 * Converts the specified java object to an ISO string.
	 * <p>
	 * The string generated by this method has all information necessary for it to be converted
	 * back to the original object.
	 *
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 */
	static String toISOString(Object object)
	{
		if (object == null)
			return "";
		Class<?> type = object.getClass();
		return getConverter(type).toISOString(type, object);
	}

	/**
	 * Converts the specified java object to a {@link java.lang.Number}.
	 *
	 * @param object object to be converted to a Number
	 * @return the specified object as a Number
	 */
	static Number toNumber(Object object)
	{
		return object != null ? getConverter(object.getClass()).toNumber(object.getClass(), object)
				: null;
	}

	/**
	 * Converts the specified string back to its original java object.
	 *
	 * @param <T>    type of the object that originated the specified string
	 * @param type   type of the object that originated the specified string
	 * @param string the string to be converted back to its original java object
	 * @return the object that was previously converted to the specified string
	 * @throws gate.error.ConversionException if the specified string can't be converted to its
	 *                                        original java object
	 * @see Converter#toString
	 */
	static <T> T fromString(Class<T> type, String string) throws ConversionException
	{
		return type.cast(fromString((Type) type, string));
	}

	/**
	 * Converts the specified string back to its original java object.
	 *
	 * @param type   type of the object that originated the specified string
	 * @param string the string to be converted back to its original java object
	 * @return the object that was previously converted to the specified string
	 * @throws gate.error.ConversionException if the specified string can't be converted to its
	 *                                        original java object
	 * @see Converter#toString
	 */
	static Object fromString(Type type, String string) throws ConversionException
	{
		if (string == null)
			return null;
		string = string.trim();
		if (string.isEmpty())
			return null;

		return Converter.getConverter(type).ofString(type, string);
	}

	static Converter getConverter(Parameter parameter)
	{
		try
		{
			return parameter.isAnnotationPresent(gate.annotation.Converter.class)
					? parameter.getAnnotation(gate.annotation.Converter.class).value()
					  .getDeclaredConstructor().newInstance()
					: Converter.getConverter(parameter.getType());
		} catch (ReflectiveOperationException ex)
		{
			throw new AppError(ex);
		}
	}
}
