package gate.adapter.converter;

import gate.adapter.registry.ConverterRegistry;
import gate.constraint.Constraint;
import gate.error.AppError;
import gate.error.ConversionException;
import gate.lang.json.JsonScanner;
import gate.lang.json.JsonToken;
import gate.lang.json.JsonWriter;

import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.lang.reflect.Parameter;
import java.lang.reflect.Type;
import java.util.ArrayDeque;
import java.util.Deque;
import java.util.List;

/**
 * Adapts a java class to be used by the gate framework.
 */
public interface Converter
{
	/**
	 * Gets the constraints associated with the converter java type.
	 *
	 * @return a list with all the constraints associated with the converter java type
	 */
	List<Constraint.Implementation<?>> getConstraints();

	/**
	 * Converts the specified java object to a {@link java.lang.Number}.
	 *
	 * @param type   type of the object to be converted to a Number
	 * @param object object to be converted to a Number
	 * @return the specified object as a Number
	 */
	default Number toNumber(Class<?> type, Object object)
	{
		throw new UnsupportedOperationException(
				String.format("Objects of type %s can't be converted to %s.", type.getName(),
						Number.class.getName()));
	}

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method must have all information necessary for it to be
	 * converted back to the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 * @see Converter#ofString
	 */
	String toString(Class<?> type, Object object);

	/**
	 * Converts the specified java object to an ISO string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method must have all information necessary for it to be
	 * converted back to the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 * @see Converter#ofString
	 */
	default String toISOString(Class<?> type, Object object)
	{
		return toString(type, object);
	}

	/**
	 * Converts the specified string back to its original java object.
	 *
	 * @param type   type of the object that originated the specified string
	 * @param string the string to be converted back to its original java object
	 * @return the object that was previously converted to the specified string
	 * @throws gate.error.ConversionException if the specified string can't be converted to its
	 *                                        original java object
	 * @see Converter#toString
	 */
	Object ofString(Class<?> type, String string) throws ConversionException;

	/**
	 * <p>
	 * Converts the specified java object to a string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 */
	String render(Class<?> type, Object object);

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @param format a string to be used to format the specified object
	 * @return the specified object as a java string
	 */
	String render(Class<?> type, Object object, String format);

	/**
	 * Reads an object of the converter-associated type from the specified
	 * {@link gate.lang.json.JsonScanner}.
	 *
	 * @param jsonScanner scanner from where the JSON object must be read
	 * @param type        type of the enumeration or collection element to be read
	 * @param elementType type of the element of the object if the object is a collection or null if
	 *                    not
	 * @return the JSON object read as a java object of the converter-associated type
	 * @throws gate.error.ConversionException if the next element of the specified JSONReader cannot
	 *                                        be converted to a java object of the converter-associated type.
	 */
	default Object ofJson(JsonScanner jsonScanner, Type type, Type elementType)
			throws ConversionException
	{
		switch (jsonScanner.getCurrent().getType())
		{
			case NULL:
				jsonScanner.scan();
				return null;
			case STRING:
			case NUMBER:
				Object value =
						this.ofString((Class<?>) type, jsonScanner.getCurrent().toString());
				jsonScanner.scan();
				return value;
			default:
				throw new ConversionException(
						jsonScanner.getCurrent() + " is not a " + type.getTypeName());
		}
	}

	/**
	 * Serializes the specified object on JSON notation.
	 * <p>
	 * The string generated by this method has all information necessary for it to be converted
	 * back to the original object.
	 *
	 * @param <T>    type of the java object to be serialized
	 * @param stack  tracks objects currently being serialized to prevent infinite recursion
	 * @param writer JsonWriter responsible for serializing the object
	 * @param type   type of the java object to be serialized
	 * @param object object to be serialized
	 * @throws ConversionException if the specified object cannot be serialized on JSON notation
	 */
	default <T> void toJson(Deque<Object> stack, JsonWriter writer, Class<T> type, T object) throws ConversionException
	{
		if (object != null)
			writer.write(JsonToken.Type.STRING, toString(object));
	}

	/**
	 * Serializes the specified object on JSON notation.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need
	 * for it to have enough information to restore the original object.
	 *
	 * @param <T>    type of the java object to be serialized
	 * @param stack  tracks objects currently being serialized to prevent infinite recursion
	 * @param writer JsonWriter responsible for serializing the object
	 * @param type   type of the java object to be serialized
	 * @param object object to be serialized
	 * @throws ConversionException if the specified object cannot be serialized on JSON notation
	 */
	default <T> void toJsonText(Deque<Object> stack, JsonWriter writer, Class<T> type, T object)
			throws ConversionException
	{
		if (object != null)
			writer.write(JsonToken.Type.STRING, render(object));
	}

	/**
	 * Gets the converter associated with the specified java class.
	 *
	 * @param type java class whose associated converted must be returned
	 * @return the converter associated with the specified java class
	 */
	static Converter getConverter(Class<?> type) {return ConverterRegistry.INSTANCE.get(type);}

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The string generated by this method has all information necessary for it to be converted
	 * back to the original object.
	 *
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 */
	static String toString(Object object)
	{
		if (object == null)
			return "";
		Class<?> type = object.getClass();
		return getConverter(type).toString(type, object);
	}

	/**
	 * Converts the specified java object to an ISO string.
	 * <p>
	 * The string generated by this method has all information necessary for it to be converted
	 * back to the original object.
	 *
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 */
	static String toISOString(Object object)
	{
		if (object == null)
			return "";
		Class<?> type = object.getClass();
		return getConverter(type).toISOString(type, object);
	}

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 */
	static String render(Object object)
	{
		if (object == null)
			return "";
		Class<?> type = object.getClass();
		return getConverter(type).render(type, object);
	}

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param object object to be converted to a string
	 * @param format a string to be used to format the specified object
	 * @return the specified object as a java string
	 */
	static String render(Object object, String format)
	{
		if (object == null)
			return "";

		Class<?> type = object.getClass();
		Converter converter = getConverter(type);

		if (format == null)
			return converter.render(type, object);
		return converter.render(type, object, format);
	}

	/**
	 * Serializes the specified java object on JSON notation.
	 * <p>
	 * The specified object will be serialized as described on the specified java type associated
	 * {@link Converter}.
	 * <p>
	 * The string generated by this method has all information necessary for it to be converted
	 * back to the original object.
	 *
	 * @param object the java object to be serialized
	 * @return the specified java object serialized using JSON notation
	 * @see BooleanConverter#toJson
	 * @see NumberConverter#toJson
	 * @see StringConverter#toJson
	 * @see CollectionConverter#toJson
	 * @see ObjectConverter#toJson
	 */
	static String toJson(Object object)
	{
		if (object == null)
			return "null";

		try (StringWriter stringWriter = new StringWriter();
		     JsonWriter writer = new JsonWriter(stringWriter))
		{
			@SuppressWarnings("unchecked")
			var type = (Class<Object>) object.getClass();
			Converter converter = Converter.getConverter(type);
			converter.toJson(new ArrayDeque<>(), writer, type, object);
			return stringWriter.toString();
		} catch (IOException ex)
		{
			throw new UncheckedIOException(ex);
		}
	}

	/**
	 * Serializes the specified java object on JSON notation
	 * <p>
	 * The specified object will be serialized as described on the specified java type associated
	 * {@link Converter}.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need
	 * for it to have enough information to restore the original object.
	 *
	 * @param object the java object to be serialized
	 * @return the specified java object serialized using JSON notation
	 * @throws ConversionException if the specified object can't be serialized on JSON notation
	 * @see BooleanConverter#toJson
	 * @see NumberConverter#toJson
	 * @see StringConverter#toJson
	 * @see CollectionConverter#toJson
	 * @see ObjectConverter#toJson
	 */
	static String toJsonText(Object object) throws ConversionException
	{
		if (object == null)
			return "";

		try (StringWriter stringWriter = new StringWriter();
		     JsonWriter writer = new JsonWriter(stringWriter))
		{
			@SuppressWarnings("unchecked")
			var type = (Class<Object>) object.getClass();
			Converter converter = Converter.getConverter(type);
			converter.toJsonText(new ArrayDeque<>(), writer, type, object);
			return stringWriter.toString();
		} catch (IOException ex)
		{
			throw new ConversionException(ex.getMessage());
		}
	}

	/**
	 * Converts the specified java object to a {@link java.lang.Number}.
	 *
	 * @param object object to be converted to a Number
	 * @return the specified object as a Number
	 */
	static Number toNumber(Object object)
	{
		return object != null ? getConverter(object.getClass()).toNumber(object.getClass(), object)
				: null;
	}

	/**
	 * Parses the specified JSON formatted string into a java object of the specified type.
	 * <p>
	 * The JSON formatted string will be parsed as described on the specified java type associated
	 * {@link Converter}.
	 *
	 * @param <T>         type of the java object to be created
	 * @param type        type of the java object to be created
	 * @param elementType type of the element of the specified object if it is a collection or null
	 *                    if otherwise
	 * @param string      JSON formatted string to be parsed
	 * @return a java object of the specified type representing the specified JSON formatted string
	 * @throws ConversionException if the specified JSON string cannot be parsed into an object of
	 *                             the specified java type
	 * @see BooleanConverter#ofJson
	 * @see NumberConverter#ofJson
	 * @see StringConverter#ofJson
	 * @see CollectionConverter#ofJson
	 * @see ObjectConverter#ofJson
	 */
	static <T> T fromJson(Class<T> type, Type elementType, String string) throws ConversionException
	{
		if (string == null)
			return null;

		string = string.trim();
		if (string.isEmpty())
			return null;

		try (JsonScanner scanner = new JsonScanner(new StringReader(string)))
		{
			Converter converter = Converter.getConverter(type);
			return type.cast(converter.ofJson(scanner, type, elementType));
		}
	}

	/**
	 * Parses the specified JSON formatted string into a java object of the specified type.
	 * <p>
	 * The JSON formatted string will be parsed as described on the specified java type associated
	 * {@link Converter}.
	 *
	 * @param <T>    type of the java object to be created
	 * @param type   type of the java object to be created
	 * @param string JSON formatted string to be parsed
	 * @return a java object of the specified type representing the specified JSON formatted string
	 * @throws ConversionException if the specified JSON string cannot be parsed into an object of
	 *                             the specified java type
	 * @see BooleanConverter#ofJson
	 * @see NumberConverter#ofJson
	 * @see StringConverter#ofJson
	 * @see CollectionConverter#ofJson
	 * @see ObjectConverter#ofJson
	 */
	static <T> T fromJson(Class<T> type, String string) throws ConversionException
	{
		return Converter.fromJson(type, null, string);
	}

	/**
	 * Converts the specified string back to its original java object.
	 *
	 * @param <T>    type of the object that originated the specified string
	 * @param type   type of the object that originated the specified string
	 * @param string the string to be converted back to its original java object
	 * @return the object that was previously converted to the specified string
	 * @throws gate.error.ConversionException if the specified string can't be converted to its
	 *                                        original java object
	 * @see Converter#toString
	 */
	static <T> T fromString(Class<T> type, String string) throws ConversionException
	{
		if (string == null)
			return null;
		string = string.trim();
		if (string.isEmpty())
			return null;

		return type.cast(Converter.getConverter(type).ofString(type, string));
	}

	static Converter getConverter(Parameter parameter)
	{
		try
		{
			return parameter.isAnnotationPresent(gate.annotation.Converter.class)
					? parameter.getAnnotation(gate.annotation.Converter.class).value()
					  .getDeclaredConstructor().newInstance()
					: Converter.getConverter(parameter.getType());
		} catch (ReflectiveOperationException ex)
		{
			throw new AppError(ex);
		}
	}
}