package gate.adapter.renderer;

import gate.adapter.registry.RendererRegistry;
import gate.error.AppError;

import java.lang.reflect.Parameter;

/**
 * Adapts a java class to be used by the gate framework.
 */
public interface Renderer
{
	/**
	 * <p>
	 * Converts the specified java object to a string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 */
	String render(Class<?> type, Object object);

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @param format a string to be used to format the specified object
	 * @return the specified object as a java string
	 */
	String render(Class<?> type, Object object, String format);


	/**
	 * Gets the converter associated with the specified java class.
	 *
	 * @param type java class whose associated converted must be returned
	 * @return the converter associated with the specified java class
	 */
	static Renderer getRenderer(Class<?> type) {return RendererRegistry.INSTANCE.get(type);}

	static Renderer getRenderer(Parameter parameter)
	{
		try
		{
			return parameter.isAnnotationPresent(gate.annotation.Renderer.class)
					? parameter.getAnnotation(gate.annotation.Renderer.class).value()
					  .getDeclaredConstructor().newInstance()
					: Renderer.getRenderer(parameter.getType());
		} catch (ReflectiveOperationException ex)
		{
			throw new AppError(ex);
		}
	}
}