package gate.adapter.renderer;

import gate.adapter.converter.*;
import gate.adapter.registry.RendererRegistry;
import gate.error.AppError;
import gate.error.ConversionException;
import gate.lang.json.JsonToken;
import gate.lang.json.JsonWriter;

import java.io.IOException;
import java.io.StringWriter;
import java.lang.reflect.Parameter;
import java.util.ArrayDeque;
import java.util.Deque;

/**
 * Adapts a java class to be used by the gate framework.
 */
public interface Renderer
{
	/**
	 * <p>
	 * Converts the specified java object to a string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 */
	String render(Class<?> type, Object object);

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The object to be converted must be of the converter-associated java type.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param type   type of the object to be converted to a string
	 * @param object object to be converted to a string
	 * @param format a string to be used to format the specified object
	 * @return the specified object as a java string
	 */
	String render(Class<?> type, Object object, String format);

	/**
	 * Serializes the specified java object on JSON notation
	 * <p>
	 * The specified object will be serialized as described on the specified java type associated
	 * {@link Converter}.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need
	 * for it to have enough information to restore the original object.
	 *
	 * @param object the java object to be serialized
	 * @return the specified java object serialized using JSON notation
	 * @throws ConversionException if the specified object can't be serialized on JSON notation
	 * @see gate.adapter.jsonConverter.BooleanJsonConverter#toJson
	 * @see gate.adapter.jsonConverter.NumberJsonConverter#toJson
	 * @see gate.adapter.jsonConverter.StringJsonConverter#toJson
	 * @see gate.adapter.jsonConverter.CollectionJsonConverter#toJson
	 * @see gate.adapter.jsonConverter.ObjectJsonConverter#toJson
	 */
	static String toJsonText(Object object) throws ConversionException
	{
		if (object == null)
			return "";

		try (StringWriter stringWriter = new StringWriter();
		     JsonWriter writer = new JsonWriter(stringWriter))
		{
			@SuppressWarnings("unchecked")
			var type = (Class<Object>) object.getClass();
			Renderer renderer = Renderer.getRenderer(type);
			renderer.toJsonText(new ArrayDeque<>(), writer, type, object);
			return stringWriter.toString();
		} catch (IOException ex)
		{
			throw new ConversionException(ex.getMessage());
		}
	}

	/**
	 * Gets the converter associated with the specified java class.
	 *
	 * @param type java class whose associated converted must be returned
	 * @return the converter associated with the specified java class
	 */
	static Renderer getRenderer(Class<?> type) {return RendererRegistry.INSTANCE.get(type);}

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param object object to be converted to a string
	 * @return the specified object as a java string
	 */
	static String render(Object object)
	{
		if (object == null)
			return "";
		Class<?> type = object.getClass();
		return getRenderer(type).render(type, object);
	}

	/**
	 * Serializes the specified object on JSON notation.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need
	 * for it to have enough information to restore the original object.
	 *
	 * @param <T>    type of the java object to be serialized
	 * @param stack  tracks objects currently being serialized to prevent infinite recursion
	 * @param writer JsonWriter responsible for serializing the object
	 * @param type   type of the java object to be serialized
	 * @param object object to be serialized
	 * @throws ConversionException if the specified object cannot be serialized on JSON notation
	 */
	default <T> void toJsonText(Deque<Object> stack, JsonWriter writer, Class<T> type, T object)
			throws ConversionException
	{
		if (object != null)
			writer.write(JsonToken.Type.STRING, render(object));
	}

	/**
	 * Converts the specified java object to a string.
	 * <p>
	 * The string generated by this method is intended to be read by humans, and there is no need for
	 * it to have enough information to restore the original object.
	 *
	 * @param object object to be converted to a string
	 * @param format a string to be used to format the specified object
	 * @return the specified object as a java string
	 */
	static String render(Object object, String format)
	{
		if (object == null)
			return "";

		Class<?> type = object.getClass();
		Renderer renderer = getRenderer(type);

		if (format == null)
			return renderer.render(type, object);
		return renderer.render(type, object, format);
	}

	static Renderer getRenderer(Parameter parameter)
	{
		try
		{
			return parameter.isAnnotationPresent(gate.annotation.Renderer.class)
					? parameter.getAnnotation(gate.annotation.Renderer.class).value()
					  .getDeclaredConstructor().newInstance()
					: Renderer.getRenderer(parameter.getType());
		} catch (ReflectiveOperationException ex)
		{
			throw new AppError(ex);
		}
	}
}
