alter table Org change sun$time1 sun__min time;
ALTER TABLE Org ADD sun$time1 time GENERATED ALWAYS AS (sun__min) VIRTUAL;
alter table Org change sun$time2 sun__max time;
ALTER TABLE Org ADD sun$time2 time GENERATED ALWAYS AS (sun__max) VIRTUAL;
alter table Org change mon$time1 mon__min time;
ALTER TABLE Org ADD mon$time1 time GENERATED ALWAYS AS (mon__min) VIRTUAL;
alter table Org change mon$time2 mon__max time;
ALTER TABLE Org ADD mon$time2 time GENERATED ALWAYS AS (mon__max) VIRTUAL;
alter table Org change tue$time1 tue__min time;
ALTER TABLE Org ADD tue$time1 time GENERATED ALWAYS AS (tue__min) VIRTUAL;
alter table Org change tue$time2 tue__max time;
ALTER TABLE Org ADD tue$time2 time GENERATED ALWAYS AS (tue__max) VIRTUAL;
alter table Org change wed$time1 wed__min time;
ALTER TABLE Org ADD wed$time1 time GENERATED ALWAYS AS (wed__min) VIRTUAL;
alter table Org change wed$time2 wed__max time;
ALTER TABLE Org ADD wed$time2 time GENERATED ALWAYS AS (wed__max) VIRTUAL;
alter table Org change thu$time1 thu__min time;
ALTER TABLE Org ADD thu$time1 time GENERATED ALWAYS AS (thu__min) VIRTUAL;
alter table Org change thu$time2 thu__max time;
ALTER TABLE Org ADD thu$time2 time GENERATED ALWAYS AS (thu__max) VIRTUAL;
alter table Org change fri$time1 fri__min time;
ALTER TABLE Org ADD fri$time1 time GENERATED ALWAYS AS (fri__min) VIRTUAL;
alter table Org change fri$time2 fri__max time;
ALTER TABLE Org ADD fri$time2 time GENERATED ALWAYS AS (fri__max) VIRTUAL;
alter table Org change sat$time1 sat__min time;
ALTER TABLE Org ADD sat$time1 time GENERATED ALWAYS AS (sat__min) VIRTUAL;
alter table Org change sat$time2 sat__max time;
ALTER TABLE Org ADD sat$time2 time GENERATED ALWAYS AS (sat__max) VIRTUAL;