this.name=Organization
orgID.description=Enter the organization name.
name.description=Enter the organization's legal name.
description.description=Enter the organization description.
icon.description=Enter the organization logo.
sun.description=Organization business hours on Sundays.
mon.description=Organization business hours on Mondays.
tue.description=Organization business hours on Tuesdays.
wed.description=Organization business hours on Wednesdays.
thu.description=Organization business hours on Thursdays.
fri.description=Organization business hours on Fridays.
sat.description=Organization business hours on Saturdays.
